#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

# runApplication $application

# Run in parallel (4 cores)
decomposePar
mpirun -n `getNumberOfProcessors` `getApplication` -parallel | tee log.solver			
reconstructPar